<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Sortie;

/**
 * SortieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SortieRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSortiesOrganisateur($id)
    {
        $em = $this->getEntityManager();
        $queryBuilder = $em->createQueryBuilder();
        $queryBuilder->select(["sorties"])
            ->from(Sortie::class, "sorties")
            ->where("sorties.organisateur = $id");

        return $queryBuilder->getQuery()->getResult();
    }

    public function getSortiesPassees()
    {
        $today = new \DateTime('now');
        $em = $this->getEntityManager();
        $queryBuilder = $em->createQueryBuilder();
        $queryBuilder->select(["sorties"])
            ->from(Sortie::class, "sorties")
            ->where("sorties.datedebut <= :today")
            ->setParameter('today', $today->format('Y-m-d'));

        return $queryBuilder->getQuery()->getResult();
    }
}
