<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Sortie;
use Doctrine\ORM\Query\Expr;

/**
 * SortieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SortieRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllExceptArchived()
    {
        $today = new \DateTime('now');
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb->select("s")
            ->from(Sortie::class, "s")
            ->where("DATE_DIFF(:today, s.datedebut) <= 30 ")
            ->setParameter('today', $today->format('Y-m-d'));
        return $qb->getQuery()->getResult();
    }

    public function getSortiesOrganisateur($id)
    {
        $em = $this->getEntityManager();
        $queryBuilder = $em->createQueryBuilder();
        $queryBuilder->select(["sorties"])
            ->from(Sortie::class, "sorties")
            ->where("sorties.organisateur = $id");

        return $queryBuilder->getQuery()->getResult();
    }

    public function getSortiesPassees()
    {
        $today = new \DateTime('now');
        $em = $this->getEntityManager();
        $queryBuilder = $em->createQueryBuilder();
        $queryBuilder->select(["sorties"])
            ->from(Sortie::class, "sorties")
            ->where("sorties.datedebut <= :today")
            ->setParameter('today', $today->format('Y-m-d'));

        return $queryBuilder->getQuery()->getResult();
    }

    public function getSortiesFiltreDate($dateDebut, $dateFin)
    {
        $em = $this->getEntityManager();
        $queryBuilder = $em->createQueryBuilder();
        $queryBuilder->select(["sorties"])
            ->from(Sortie::class, "sorties")
            ->where("sorties.datedebut BETWEEN :debut AND :fin")
            ->setParameter('debut', $dateDebut)
            ->setParameter('fin', $dateFin);

        return $queryBuilder->getQuery()->getResult();
    }

    public function getSortiesInscrit($id)
    {

    }

    public function getSortiesNonInscrit($id)
    {

    }
}
