<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Sortie;

/**
 * SortieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SortieRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSortiesBySite($site)
    {
        $em = $this->getEntityManager();
        $queryBuilder = $em->createQueryBuilder();
        $queryBuilder->select(["sortie"])
            ->from(Sortie::class, "sorties")
            ->where("site.nom = $site");

        return $queryBuilder->getQuery()->getResult();
    }
}
